version: '3'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb10.6
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_ROOT_HOST=%
      - MARIADB_DATABASE=board
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    restart: always
    volumes:
    - ./docker/mariadb/sql:/data/sql
  sonarqube:
    image: amd64/sonarqube:7.9.1-community
    container_name: sonarqube7.9.1
    ports:
      - "9000:9000"
    depends_on:
      - "postgres"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_HOME=/opt/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - ./docker/sonarqube/conf:/opt/sonarqube/conf
      - ./docker/sonarqube/data:/opt/sonarqube/data
      - ./docker/sonarqube/logs:/opt/sonarqube/logs
      - ./docker/sonarqube/extensions:/opt/sonarqube/extensions
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./docker/sonarqube/postgres:/var/lib/postgresql/data
networks:
  sonarnet:
    driver: bridge
