spring:
  devtools:
    add-properties: true
    restart:
      enabled: true

  jta:
    atomikos:
      datasource:
        board:
          xa-properties:
            user: root
            password: root
            url: "jdbc:mariadb://localhost:3306/board"
        file:
          xa-properties:
            user: root
            password: root
            url: "jdbc:mariadb://localhost:3306/file"

springdoc:
  swagger-ui:
    enabled: true
  show-actuator: true

logging:
  config: classpath:logback-local.xml
  level:
    web: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    io.swagger.models.parameters.AbstractSerializableParameter: error