spring:
  devtools:
    add-properties: true
    restart:
      enabled: true

springdoc:
  swagger-ui:
    enabled: true
  show-actuator: true

logging:
  config: classpath:logback-local.xml
  level:
    web: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    io.swagger.models.parameters.AbstractSerializableParameter: error